ui-onboarding:
  welcomeNoticeVersion: 2026-08-13.1
locale:
  preference: zh
agent-default-model:
  provider: scnet
  model: DeepSeek-V4-Flash-0731
llm-pi-ai:
  providers:
    opencode:
      apiKeyEnv: OPENCODE_API_KEY
      models:
        - id: deepseek-v4-flash-free
          name: DeepSeek V4 Flash Free
          contextWindow: 200000
          maxTokens: 128000
        - id: mimo-v2.5-free
          name: MiMo V2.5 Free
          contextWindow: 200000
          maxTokens: 32000
        - id: nemotron-3-ultra-free
          name: Nemotron 3 Ultra Free
          contextWindow: 1000000
          maxTokens: 128000
    scnet:
      apiKeyEnv: SCNET_API_KEY
      api: openai-completions
      baseURL: https://api.scnet.cn/api/llm/v1
      retryPolicy:
        mode: normal
        maxRetries: 100
        retryableCodes: [ RATE_LIMIT ]
        backoff:
          initialDelayMs: 500
          maxDelayMs: 5000
          jitterRatio: 0.1
      models:
        - id: GLM-5.2-Base
        - id: MiniMax-M2.5
        - id: Qwen3.5-122B-A10B
        - id: Qwen3.8-Max
        - id: Qwen3-30B-A3B-Instruct-2507
        - id: DeepSeek-V4-Flash-0731
        - id: Qwen3-235B-A22B
        - id: Kimi-K2.6
        - id: MiniMax-M3
        - id: DeepSeek-R1-Distill-Qwen-7B
        - id: DeepSeek-R1-Distill-Qwen-32B
        - id: DeepSeek-R1-Distill-Llama-70B
        - id: DeepSeek-V4-Pro
        - id: Kimi-K2.7-Base
        - id: SCNet-Max
        - id: Qwen3.6-Max
        - id: Kimi-K2.5
        - id: Qwen3.7-Plus
        - id: Kimi-K3
        - id: GLM-5.2
        - id: Kimi-K2.7-Code
        - id: GLM-5
        - id: Qwen3-30B-A3B
        - id: QwQ-32B
        - id: Qwen3-235B-A22B-Thinking-2507
        - id: MiMo-V2.5-Pro
        - id: MiniMax-M2.7
        - id: GLM-5.1
        - id: Qwen3.6-Flash
        - id: GLM-5-Base
        - id: Qwen3.6-27B
        - id: Qwen3-Embedding-8B
        - id: Qwen3.6-Plus
        - id: Qwen3.7-Max
        - id: GLM-5.1-Base
        - id: DeepSeek-V4-Flash
    nvidia:
      apiKeyEnv: NVIDIA_API_KEY
      retryPolicy:
        mode: normal
        maxRetries: 100
        retryableCodes: [ RATE_LIMIT ]
        backoff:
          initialDelayMs: 500
          maxDelayMs: 5000
          jitterRatio: 0.1
